### ISSUE TITLE
OSS Client/Backend?

### ISSUE THREAD

**Issue by DuncanHills** [overtrack-gg/overtrack-web#77]
Hello, I see a lot of potential utility for OverTrack despite its niche userbase. This is obviously a good candidate for OSS software, and I'm glad you all have decided to open-source the web frontend along with some other things. However, neither the desktop client nor the backend are open-sourced.

Firstly, this limits the utility of what can be done by contributors. For instance, I have a good deal of experience with highly-linked complex graph databases. The OverTrack dataset lines up nicely with this, and I would be happy to contribute, but that area of the codebase is opaque and hidden.

Secondly, it seems a bit disingenuous to open-source just the superficial bits of the site without the interesting bits. This seems a bit like asking for randos to help maintain the site without really getting much in return.

Would the OverTrack team consider open-sourcing the rest of the application?

**Comment by benolot** [comment]
Will leave this for @synap5e to answer, but I think the short answer (Although synap5e will have the final say on this) is probably no because OT is still a for-profit business, but again, synap5e is the authority on this 😄

**Comment by DuncanHills** [comment]
I'd like to set the stage for this conversation correctly since you're at least open for discussion. Firstly, it should be known that I think OverTrack is a great project no matter which incarnation it takes as far as its open-source model. Otherwise I would not be here posting.

Secondly, I'd like to dispel the notion that software cannot be both open-source and at the core of a for-profit company. There are many successful models out there that show this is possible. This may be obvious to many people already, but I'll elaborate just for posterity and clarity. Having participated in a number of early-stage startups and even co-founding one myself, I can say with certainty that a) developers are expensive and b) time is always of the essence. These two things are directly correlated with one another. While I think OverTrack is a great concept and wish it the best of luck in every way, I also believe there is definitely a ceiling to the scale and market size for a product of this nature. By having the core be open-source while the business itself is focused on delivering a reliable and convenient product, I believe OverTrack may be able to develop rapidly and keep up with the fast-moving game release cycle while also maximizing its market share.

Thirdly, I think it would be fun to hack on the backend for the benefit of the Overwatch community and I'm sure a few other developers out there might as well. :)

**Comment by synap5e** [comment]
I would really like to make OverTrack work with an open source client, although there are some heavy considerations going into that.

My main concern is that a competitor would be able to use the public source to boost themselves forward and take over the space. Because I am developing and bootstrapping OverTrack on my own as opposed to being a VC backed startup, I am not really able to compete with the SEO and marketing of other projects products in the same space. Specifically, Visor and Pursuit were similar trackers for Overwatch that got far more brand recognition and "talk factor", despite (in my personal opinion) being less accurate or detailed than OT.
I have invested a lot in this project in unpaid time and other bootstrap costs, so having a "secret sauce" is somewhat intended to prevent someone else from taking that investment and using it to build their own platform/product.

Once OT has significantly more brand recognition and publicity, I am hoping that it will become more practical to open source the client. If OT is much more well known, established, and ideally integrated into the gaming ecosystem (e.g. scrimming, coaching, tournament, etc. integrations), I'm hoping the "tech barrier" will be less significant and required.

Another consideration is that, since my goal is to be able to sustain myself in developing this, a hard fork of the OT project would be devastating. This would be even worse if such a fork were to remove the ability for me to offer subscription only perks or features, which would be entirely possible if the backend were open sourced. Perhaps as the offering of OT changes (e.g. into including aggregated/avg statistics etc.) this would be somewhat mitigated but, for now, the subscriber-only features wouldn't work well if someone could just set up an "overtrack but all features free" forked backend.

For these reasons my current response to an open source client would be *"not yet"*, and for backend that would be something to reconsider much further down the track (i.e. after the client has been open source for some time).

I am really keen on letting people hack around with things, and have some plans for how that could be done. I have tried to make things very developer friendly when I can (e.g. in the `/games` APIs), and have some ideas going forward on how to let people hook into game started/ended events, or even in adding plugin support to track new games utilizing the OT client's framework.
